language: python

before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq libpoppler-cpp-dev unpaper tesseract-ocr

sudo: false

matrix:
    include:
        - python: "3.5"
        - python: "3.6"
        - python: "3.7-dev"
        - stage: build_docker
          name: amd64 docker build
          services:
            - docker
          script:
            - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            - docker build -f Dockerfile --tag=${DOCKER_TAG}:amd64 .
            - docker push ${DOCKER_TAG}:amd64
        - stage: build_docker
          name: arm64v8 docker build
          services:
            - docker
          script:
            - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            - travis_wait 60 docker build -f Dockerfile --tag=${DOCKER_TAG}:arm64v8 .
            - docker push ${DOCKER_TAG}:arm64v8
          arch: arm64
        - stage: build_docker
          name: arm32v7 docker build
          services:
            - docker
          script:
            - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            # register binfmt stuff for qemu-static binaries so we can use userland-emulation
            - docker run --rm --privileged multiarch/qemu-user-static:register --reset
            # replace the multi-arch reference with a specific, arm32v7 version. else docker will use the platform specific one,
            # which is amd64.
            - sed -i 's/FROM alpine:3.10/FROM alpine@sha256:2632d6288d34d7175021683f6e363fa7c0fa8866a565eb285e36e3b856545e82/g' Dockerfile
            - sed -i 's/#REMOVEMEINARM32//g' Dockerfile
            - travis_wait 60 docker build -f Dockerfile --tag=${DOCKER_TAG}:arm32v7 .
            - docker push ${DOCKER_TAG}:arm32v7
        - stage: build_docker
          name: arm32v6 docker build
          services:
            - docker
          script:
            - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            # register binfmt stuff for qemu-static binaries so we can use userland-emulation
            - docker run --rm --privileged multiarch/qemu-user-static:register --reset
            # replace the multi-arch reference with a specific, arm32v6 version. else docker will use the platform specific one,
            # which is amd64.
            - sed -i 's/FROM alpine:3.10/FROM alpine@sha256:9afbfccb806687f6979661622f0c04dc534769e742465b107f84a830cbb8e77a/g' Dockerfile
            # the arm32 qemu binaries work for for both v6 and v7
            - sed -i 's/#REMOVEMEINARM32//g' Dockerfile
            - travis_wait 60 docker build -f Dockerfile --tag=${DOCKER_TAG}:arm32v6 .
            - docker push ${DOCKER_TAG}:arm32v6
        - stage: publish_manifest
          env:
            - DOCKER_CLI_EXPERIMENTAL=enabled
          services:
            - docker
          script:
            - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            - docker manifest create ${DOCKER_TAG}:latest ${DOCKER_TAG}:amd64 ${DOCKER_TAG}:arm64v8 ${DOCKER_TAG}:arm32v7 ${DOCKER_TAG}:arm32v6
            - docker manifest annotate ${DOCKER_TAG}:latest ${DOCKER_TAG}:arm32v6 --os linux --arch arm --variant v6
            - docker manifest annotate ${DOCKER_TAG}:latest ${DOCKER_TAG}:arm32v7 --os linux --arch arm --variant v7
            - docker manifest annotate ${DOCKER_TAG}:latest ${DOCKER_TAG}:arm64v8 --os linux --arch arm64 --variant v8
            - docker manifest push --purge ${DOCKER_TAG}:latest

install:
    - pip install --upgrade pip pipenv sphinx
    - pipenv lock -r > requirements.txt
    - pip install -r requirements.txt

script:
    - cd src/
    - pytest --cov
    - pycodestyle
    - sphinx-build -b html ../docs ../docs/_build -W

after_success:
  - coveralls

deploy:
  - provider: script
    skip_cleanup: true
    script: ci/deploy-docker
    on:
      tags: true
      condition: '"${BUILD_DOCKER}" = 1'
  - provider: script
    skip_cleanup: true
    script: ci/deploy-docker
    on:
      branch: master
      condition: '"${BUILD_DOCKER}" = 1'
  - provider: script
    skip_cleanup: true
    script: ci/deploy-docker
    on:
      branch: "feature/multi-arch-docker-build"
      condition: '"${BUILD_DOCKER}" = 1'
