language: python

before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq libpoppler-cpp-dev unpaper tesseract-ocr

sudo: false

matrix:
    include:
        - python: "3.5"
        - python: "3.6"
        - python: "3.7-dev"
        - env:
            - BUILD_DOCKER=1
            # Variable to add to publish the Docker image:
            # * DOCKER_USERNAME
            # * DOCKER_PASSWORD, to be encrypted, use `travis encrypt DOCKER_PASSWORD=<password>`
          services:
            - docker
          script:
            - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            - docker run --rm --privileged multiarch/qemu-user-static:register --reset
            - docker build -f Dockerfile.amd64 --tag=moztr/paperless-travis:amd64 .
            - docker push moztr/paperless-travis:amd64
          stage: build_docker
        - stage: build_docker
          services:
            - docker
          script:
            - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            - travis_wait 60 docker build -f Dockerfile --tag=moztr/paperless-travis:arm64v8 .
            - docker push moztr/paperless-travis:arm64v8
          arch: arm64
        - stage: build_docker
          services:
            - docker
          script:
            - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            - docker run --rm --privileged multiarch/qemu-user-static:register --reset
            - travis_wait 60 docker build -f Dockerfile.arm32v7 --tag=moztr/paperless-travis:arm32v7 .
            - docker push moztr/paperless-travis:arm32v7
        - stage: publish_manifest
          services:
            - docker
          script:
            - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            - mkdir ~/.docker || echo "exists already, ok"
            - 'echo "{ \"experimental\" : \"enabled\" }" > ~/docker/config.json'
            - docker manifest create moztr/paperless-travis:latest moztr/paperless-travis:amd64 moztr/paperless-travis:arm64v8 moztr/paperless-travis:arm32v7
            - docker manifest annotate moztr/paperless-travis:latest moztr/paperless-travis:arm32v7 --os linux --arch arm
            - docker manifest annotate moztr/paperless-travis:latest moztr/paperless-travis:arm64v8 --os linux --arch arm64 --variant v8
            - docker manifest push --purge moztr/paperless-travis:latest

install:
    - pip install --upgrade pip pipenv sphinx
    - pipenv lock -r > requirements.txt
    - pip install -r requirements.txt

script:
    - cd src/
    - pytest --cov
    - pycodestyle
    - sphinx-build -b html ../docs ../docs/_build -W

after_success:
  - coveralls

deploy:
  - provider: script
    skip_cleanup: true
    script: ci/deploy-docker
    on:
      tags: true
      condition: '"${BUILD_DOCKER}" = 1'
  - provider: script
    skip_cleanup: true
    script: ci/deploy-docker
    on:
      branch: master
      condition: '"${BUILD_DOCKER}" = 1'
  - provider: script
    skip_cleanup: true
    script: ci/deploy-docker
    on:
      branch: "feature/multi-arch-docker-build"
      condition: '"${BUILD_DOCKER}" = 1'
